require 'pathname'
require 'yaml'

module SchemaDev
  TRAVIS_FILE = ".travis.yml"

  module Travis
    extend self

    def build(config)
      env = 'POSTGRESQL_DB_USER=postgres MYSQL_DB_USER="travis"'
      gemfiles = config.matrix.map{|entry| GemfileSelector.gemfile(entry.slice(:rails, :db)).to_s}.uniq
      exclude = config.matrix(excluded: :only).map { |entry| {}.tap {|ex|
        ex["rvm"] = entry[:ruby]
        ex["gemfile"] = GemfileSelector.gemfile(entry.slice(:rails, :db)).to_s
        ex["env"] = env if config.dbms.any?
      }}.reject{|ex| not gemfiles.include? ex["gemfile"]}

      {}.tap { |travis|
        travis["rvm"] = config.ruby.sort
        travis["gemfile"] = gemfiles.sort
        if config.dbms.any?
          travis["before_script"] = 'bundle exec rake create_databases'
          travis["after_script"] = 'bundle exec rake drop_databases'
          travis["env"] = env
        end
        travis["notifications"] = { "email" => config.notify } if config.notify.any?
        travis["matrix"] = { "exclude" => exclude.sort_by{|ex| [ex["rvm"], ex["gemfile"]]} } if exclude.any?
      }
    end

    def update(config)
      filepath = Pathname.new(TRAVIS_FILE)
      newtravis = build(config)
      oldtravis = YAML.load(filepath.read) rescue nil
      if oldtravis != newtravis
        header = <<-ENDYAML
# This file was auto-generated by the schema_dev tool, based on the data in
#                 ./schema_dev.yml 
# Please do not edit this file; any changes will be overwritten next time
# schema_dev gets run.
ENDYAML
        filepath.write header + newtravis.to_yaml
        puts "* Updated #{filepath}"
      end
    end
  end
end
