name: CI PR Builds

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']
        activesupport: ['5.2', '6.0', '6.1', '7.0']
        exclude:
          - ruby: '2.5'
            activesupport: '7.0'
          - ruby: '2.6'
            activesupport: '7.0'
          - ruby: '3.0'
            activesupport: '5.2'
          - ruby: '3.1'
            activesupport: '5.2'
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/Gemfile.activesupport-${{ matrix.activesupport }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: 'Run bundle update'
        run: bundle update

      - name: Run tests
        run: bundle exec rake spec

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.ruby }}-${{ matrix.activesupport }}
          parallel: true
  finish:
    needs: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
